post/urls.py
# post/urls.py
from django.urls import path
from .views import post_list, post_details, author_details, author_list, add_post, create_p, add_autor, create_a

app_name = 'posts'
urlpatterns = [
   path('', post_list,),
   path('<int:p>', post_details, name = 'details'),
   path('author_details/<int:a>', author_details, name = 'details_a'),
   path('author_list', author_list),
   path('add_post', add_post),
   path('add_autor', add_autor),
   path('create_p', create_p),
   path('create_a', create_a),
   ]

posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
print(settings.STATIC_ROOT)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("post.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/models.py
from django.db import models

class Author(models.Model):
    nick = models.CharField(max_length=50, blank=False, null=False, unique=True)
    email = models.EmailField(max_length=254, blank=False, unique = True, null=True)

    def __str__(self):
        return f"id:{self.id}, nick={self.nick}, email={self.email}"
    class Meta:
        ordering = ['nick']

class Posts(models.Model):
    title   =  models.CharField(max_length = 256, blank=False)
    content =  models.TextField(blank=False)
    created =  models.DateTimeField(auto_now_add = True)
    modified = models.DateTimeField(auto_now=True)
    author_id =models.ForeignKey(Author, on_delete=models.CASCADE )


    def __str__(self):
        return f"id:{self.id}, title={self.title}, content={self.content}, created={self.created}, author_id = {self.author_id}"

    class Meta:
        ordering = ['created']

post/views.py
from django.http import HttpResponse
from django.template import Context, loader
from post.models import Posts, Author
from django.shortcuts import render, redirect
from post.form import AuthorForm, PostForm
from django.core.paginator import Paginator


def post_list(request):
   posty = Posts.objects.all()
   paginator = Paginator(posty, 5)
   page_number = request.GET.get('page')
   posty = paginator.get_page(page_number)
   c = {"title": "Lista postów", "posty": posty}
   return render(request, "post/main.html", c)

def post_details(request, p):
   post = Posts.objects.get(id = p)
   c = {"title": "Szczegóły posta", "post": post}
   return render(request, "post/main.html", c)

def author_list(request):
   autorzy = Author.objects.all()
   paginator = Paginator(autorzy, 5)
   page_number = request.GET.get('page')
   autorzy = paginator.get_page(page_number)
   c = {"title": "Lista autorów", 'autorzy': autorzy}
   return render(request, "post/author_list.html", c)

def author_details(request, a):
   auth = Author.objects.get(id = a)
   t = loader.get_template("post/author_details.html")
   c = {"title": "O autorze", "auth": auth}
   return HttpResponse(t.render(c))

def add_post(request):
   autorzy = Author.objects.all()
   c = {"title": "Nowy post", "autorzy": autorzy, 'form': PostForm}
   return render(request, "post/add_post.html", c)

def add_autor(request):
   autorzy = Author.objects.all()
   c = {"title": "Nowy autor", 'form': AuthorForm}
   return render(request, "post/add_autor.html", c)

def create_p(request):
   if request.method == "POST":
      dane = request.POST
      form = PostForm(dane)
      if form.is_valid():
         form.save()
   return redirect('/')

def create_a(request):
   if request.method == "POST":
      dane = request.POST
      form =AuthorForm(dane)
      if form.is_valid():
         form.save()
   return redirect('/author_list')

post/templates/post/add_autor.html
{% extends "post/header.html" %}

{% block add_autor %}

    <form method="post" style="margin-left: 50px;" action="/create_a">
        {% csrf_token %}
        <p style="font-size: 25px; margin-left: 50px">Podaj swoje dane:<br>
            {{ form }}
        <br><input type="submit" value="Dodaj" style="font-size: 25px; margin-left: 50px">
    </form>

{% endblock %}

post/templates/post/add_post.html
{% extends "post/header.html" %}

{% block add_post %}

    <form method="post" style="margin-left: 50px;" action="/create_p">
        {% csrf_token %}
        <p style="font-size: 25px; margin-left: 50px">Podaj swoje dane:<br>
            {{ form }}
        <br><input type="submit" value="Dodaj" style="font-size: 25px; margin-left: 50px">
    </form>

{% endblock %}

{% block add_autor %}

{% endblock %}

post/templates/post/author_details.html
{% extends "post/header.html" %}

{% block details_post %}
        <h1 style="margin-left: 50px">O autorze posta...</h1>
               <p style="font-size: 20px; margin-left: 60px">
                   <b>Autor:</b> {{ auth.nick }}<br><br>
                   <b>e-mail autora:&nbsp&nbsp</b> <i>{{ auth.email }}</i></p>
                <p style="font-size: 12px; margin-left: 70px"><a href='/author_list'>Lista autorów</a>, <a href='/'>Lista postów</a></p>
{% endblock %}}

post/templates/post/author_list.html
{% extends "post/header.html" %}

{% block list_authors %}
        <h1 style="margin-left: 50px">Lista autorów</h1>
            <p style="font-size: 25px; margin-left: 50px">
                   Autorzy na temat Python'a.</p>
               <p style="font-size: 20px; margin-left: 60px">
                    <ul style="font-size: 20px; margin-left: 50px">
                        {% for a in autorzy %}
                            <li><a href="{% url "posts:details_a" a.id %}">{{ a.nick }}</a></li>
                        {% endfor %}
                     </ul>
 <div class="pagination" style="font-size: 12px; margin-left: 70px">
                    <span class="step-links">
                        {% if autorzy.has_previous %}
                            <i><a href="?page=1">« pierwsza</a>
                                <a href="?page={{ autorzy.previous_page_number }}">poprzednia</a></i>
                        {% endif %}

                    <span class="current">
                        <b style="font-size: 20px"> &nbspStrona {{ autorzy.number }} / {{ autorzy.paginator.num_pages }}&nbsp</b>
                    </span>

                        {% if autorzy.has_next %}
                           <i><a href="?page={{ autorzy.next_page_number }}">następna</a>
                               <a href="?page={{ autorzy.paginator.num_pages }}">ostatnia »</a></i>
                        {% endif %}
   </span>
   </div>
                <p style="font-size: 12px; margin-left: 70px"><a href='/add_autor'>Dodaj autora</a>, <a href='/'>Lista postów</a></p>
{% endblock %}}

post/templates/post/header.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{{ title }}{% endblock %}</title>
    </head>

    <body style="background-color: lightGrey; font-family: Calibri">
    <h1>Blog o Pythonie</h1>

    <img src="{% static 'python_logo.png' %}" alt="My image"; height="30"; width="30">
    <div id="header" style="background-color: #00363a; padding: 10px; box-shadow: 3px 3px grey; margin-bottom: 10px">
        {% block header %}
        {% endblock %}
    </div>

    <div id="main" style="font-family: 'Calibri Light'">
        {% block main %}
        {% endblock %}
    </div>

    <div id="details" style="font-family: 'Calibri Light'">
        {% block details_post %}
        {% endblock %}
    </div>

    <div id="a_list" style="font-family: 'Calibri Light'">
        {% block list_authors %}
        {% endblock %}
    </div>

    <div id="add_post" style="font-family: 'Calibri Light'">
        {% block add_post %}
        {% endblock %}
    </div>

    <div id="add_autor" style="font-family: 'Calibri Light'">
        {% block add_autor %}
        {% endblock %}
    </div>

    </body>
</html>

post/templates/post/main.html
{% extends "post/header.html" %}

{% block main %}
    {% if title == "Lista postów" %}
            <h1 style="margin-left: 50px">Witaj</h1>

               <p style="font-size: 25px; margin-left: 50px">
                   Dyskusja na temat Python'a.</p>
                <ol style="font-size: 20px; margin-left: 50px">
                     {% for m in posty %}
                         <li><a href="{% url "posts:details" m.id %}">[{{ m.title }}]:&nbsp&nbsp{{ m.content|truncatewords:10 }}</a></li>
                    {% endfor %}
                </ol>
                <br>
                <div class="pagination" style="font-size: 15px; margin-left: 70px">
                    <span class="step-links">
                        {% if posty.has_previous %}
                            <i><a href="?page=1">« pierwsza</a>
                                <a href="?page={{ posty.previous_page_number }}">poprzednia</a></i>
                        {% endif %}

                    <span class="current">
                        <b style="font-size: 20px"> &nbspStrona {{ posty.number }} / {{ posty.paginator.num_pages }}&nbsp</b>
                    </span>

                        {% if posty.has_next %}
                           <i><a href="?page={{ posty.next_page_number }}">następna</a>
                               <a href="?page={{ posty.paginator.num_pages }}">ostatnia »</a></i>
                        {% endif %}
   </span>
   </div>

                <p> <a href="add_post">Dodaj nowy post</a></p>

    {% elif title == "Szczegóły posta" %}
            <h1 style="margin-left: 50px">Post nr {{ post.id }}</h1>
               <p style="font-size: 20px; margin-left: 60px">
                   <b>Temat:</b> <u>{{ post.title }}</u><br><br>
                   <b>Treść:&nbsp&nbsp</b> <i>{{ post.content }}</i></p>
               <p style="font-size: 15px; margin-left: 70px">
                   Autor: <a href="{% url "posts:details_a" post.author_id.id %}"><b>{{ post.author_id.nick }}</b></a><br>
                   Data utworzenia: {{ post.created }}<br>
                   Data modyfikacji: {{ post.modified }}<br>
               </p>
                <p style="font-size: 12px; margin-left: 70px"><a href='/'>Powrót do listy</a> </p>
    {% endif %}

{% endblock %}}

post/templates/post/post_detail.html
{% extends "post/header.html" %}

{% block title %}{{ title }}{% endblock %}

{% block detail_post %}

{% endblock %}